const governments = [
    'Cairo',
    'Alexandria',
    'Giza',
    'Qalyubia',
    'Beheira',
    'Matrouh',
    'Dakahlia',
    'Kafr El-Sheikh',
    'Gharbia',
    'Menoufia',
    'Damietta',
    'Port Said',
    'Ismailia',
    'Suez',
    'Sharqia',
    'North Sinai',
    'South Sinai',
    'Fayoum',
    'Beni Suef',
    'Minya',
    'Asyut',
    'New Valley',
    'Sohag',
    'Qena',
    'Luxor',
    'Aswan',
    'Red Sea',
];
const departments = [
    'Neurology',
    'Facial Plastic Surgery',
    'Dermatology',
    'Neurosurgery',
    'Otology',
    'Ophthalmology',
    'Rhinology',
    'Oral Health',
    'Cardiology',
    'Hepatology',
    'Pulmonology',
    'Gastroenterology',
    'Urology',
    'Plastic Surgery',
    'Orthopedics',
    'Gynecology'
];

module.exports = {governments, departments}