const governments = [
    'Cairo',
    'Alexandria',
    'Giza',
    'Qalyubia',
    'Beheira',
    'Matrouh',
    'Dakahlia',
    'Kafr El-Sheikh',
    'Gharbia',
    'Menoufia',
    'Damietta',
    'Port Said',
    'Ismailia',
    'Suez',
    'Sharqia',
    'North Sinai',
    'South Sinai',
    'Fayoum',
    'Beni Suef',
    'Minya',
    'Asyut',
    'New Valley',
    'Sohag',
    'Qena',
    'Luxor',
    'Aswan',
    'Red Sea',
];
const departments = [
    'Neurology',
    'Facial Plastic Surgery',
    'Dermatology',
    'Neurosurgery',
    'Otology',
    'Ophthalmology',
    'Rhinology',
    'Oral Health',
    'Cardiology',
    'Hepatology',
    'Pulmonology',
    'Gastroenterology',
    'Urology',
    'Plastic Surgery',
    'Orthopedics',
    'Gynecology'
];
const governmentsCodes = new Set([
    '01', '02', '03', '04', '11', '12', '13', '14', '15', '16', '17', '18', '19', 
    '21', '22', '23', '24', '25', '26', '27', '28', '29', '31', '32', '33', '34', 
    '35', '88'
  ]);
module.exports = {governments, departments, governmentsCodes}